linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    # - sql
    - style
    - test
    - unused
  disable:
    - exhaustivestruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - godox
    - prealloc    # For most programs usage of prealloc will be a premature optimization.
    - gofmt       # Superseded by gofumpt
    - golint      # Deprecated
    - interfacer  # Deprecated
    - maligned    # Deprecated
    - scopelint   # Deprecated
linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - opinionated
  gofumpt:
    extra-rules: true
  govet:
    check-shadowing: true
    enable-all: true
  maligned:
    suggest-new: true
issues:
  exclude:
    - declaration of "(err|ctx)" shadows declaration at
