name: CI

on: [ push, workflow_dispatch ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit
        run: python3 -m pip install pre-commit
      - name: Run pre-commit check
        env:
          SKIP: golangci-lint
        run: pre-commit run --all-files --show-diff-on-failure --color=always

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2

  release:
    needs: [ pre-commit, lint ]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - uses: goreleaser/goreleaser-action@v2
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          version: latest
          args: build --snapshot
      - uses: actions/upload-artifact@v2
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: Snapshots
          path: |
            dist/fizzbuzz*
            dist/checksums.txt
          retention-days: 5
          if-no-files-found: error
      - uses: goreleaser/goreleaser-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          version: latest
          args: release
